articles/urls.py
from django.urls import path
from . import views
app_name = 'articles'

urlpatterns=[
    # article Read
    path('', views.index, name='index'),
    path('<int:id>/detail/', views.detail, name='detail'),

    # article Create
    path('create/', views.create, name='create'),
    # -> 처음 create를 누르면 get 방식으로 진행됨.

    # comment Create, Delete
    path('<int:article_id>/comments/create/', views.comment_create, name ='comment_create'),
    path('<int:article_id>/comments/<int:id>/delete', views.comment_delete, name = 'comment_delete'),

]

board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    # comment_set = 
    # 두 클래스가 양방향을 연결되어 있음.


# 댓글이라는 기능은 어떤 게시물에 종속되어 있음. 따로 댓글 기능만이 존재할 수 없음.
# 댓글 기능은 또 어떤 데이터를 담아야하는지 생각을 해보면 ..
# 먼저 웹상에 데이터가 어떤 형식으로 저장되어 있는지
# 9:25 쯤 캡쳐 참고
# 데이터 베이스에는 글자나 숫자만 취급 -> 여러개의 데이터를 한번에 넣을 수 없음!
# 댓글 테이블 따로 만든다고 한다면 이 댓글 컬럼이 어느 게시물에 종속이 되는지 알 수 없음.
# comment 테이블에 article_id라는 컬럼을 만들어 어떤 게시물에 속해있는지 표현 가능 
class Comment(models.Model):
    # id 도 자동으로 만들어주는 컬럼
    content = models.TextField()
    article = models.ForeignKey(Article, on_delete=models.CASCADE) # 모델과 모델을 연결해주는 기능을 함. 인자(어떤모델과 연결할지, delete설정) 
    # article_id 는 자동으로 만들어주는 컬럼
# PK(primary key or id): 고유한 값 (주민등록번호)
# FK(foreign key): 다른 테이블에 있는 id -> 지금 여기서는 article_id 에 해당하는 key 
# django 사이트 relationship field에서 자세한 문서 확인 
# 게시물을 삭제할 때 댓글도 같이 삭제할지 or 분석할 때 사용할 수 있는 데이터인데 유지할지
# 이를 위한 설정
# - cascade, set_null, set_default 

articles/forms.py
from django import forms
from .models import Article
from .models import Comment

class ArticleForm(forms.ModelForm):
    # articleform 클래스는 
    class Meta:
        model = Article
        # fields -> Article 이 가지고 있는 모든 column 들을 입력 받을 거야!
        fields='__all__'

# ModelForm: 해당하는 모델에 어울리는 input태그를 만들어줌
# Meta: 그 외의 정보들을 다 넣어주는 클래스 ArticleForm 클래스에 넣어서 그에 맞는 폼을 만드는 데 도움을 줌.
# 메타정보: 그 사진의 정보들, 사진 찍은 날짜, 장소, 같이 찍은 사람


class CommentForm(forms.ModelForm):
    class Meta:
        model= Comment
        # fields='__all__'
        # content만 보여줄거야 
        # fields = ('content',)
        exclude = ('article',)

        # fields => 추가할 필드 이름 목록
        # exclude => 제외할 필드 이름 목록

articles/views.py
from django.shortcuts import render, redirect
from .models import Article, Comment 
from .forms import ArticleForm, CommentForm

# Create your views here.
def index(request):
    articles = Article.objects.all()

    context ={
        'articles': articles,
    }
    
    return render(request, 'index.html', context)


def detail(request, id):
    article = Article.objects.get(id=id)
    comment_form = CommentForm()

    # comment 목록 조회 
    # 1. 첫번째 방법
    # comment_list = Comment.objects.filter(article=article)

    # 2. 두번째 방법 (Comment에 article이 연결되있기 때문에 그 반대도 연결되어 있음)
    # 현재 article이라는 변수에는 현재 특정 id에 해당하는 article 정보가 저장되어 있음.
    # comment_list = article.comment_set.all()

    # 3. 세번쨰 방법
    # html 코드에서 article.comment_set.all 로 직접 변수 입력
    # -> 이 방법이 data 관개설정을 잘 이용하는 방법 


    # context 딕셔너리 안의 key와 html 안의 변수의 이름이 같아야 함.
    context = {
        'article': article,
        'comment_form': comment_form,
        # 'comment_list': comment_list,
    }

    return render(request, 'detail.html', context)



# 코드를 짤 때 코드가 진행되는 순서대로 작성하면서 진행 반복
# -> 오류가 났을 때 순서대로 수정해볼 수 있음.
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save()
            return redirect('articles:index')
    else:
        form = ArticleForm()

    context = {
        'form': form,
    }
    return render(request, 'form.html' , context)
    # modelform 어제 코드 보면 update, create html 파일이 완전히 똑같았음
    # 둘다 submit 후에 action칸을 비워놨기 때문에

def comment_create(request, article_id):
    # 사용자가 입력한 정보를 form에 입력 
    comment_form = CommentForm(request.POST)
        
    # 유효성 검사
    if comment_form.is_valid():
        # form 을 저장 => 추가로 넣어야 하는 데이터를 넣기 위해 저장 멈춰!
        comment=comment_form.save(commit=False)

        # 질문: 
        
        # 첫번째 방법.
        # article_id를 기준으로 article obj(article 전체정보들) 를 가져와서 
        # Comment의 article 컬럼(정보가 없음)에 저장
        article = Article.objects.get(id=article_id)
        # # article 컬럼에 추가
        comment.article = article

        # 두번째 방법 : 속도가 좀 더 빠름.
        # comment.article_id = article_id # -> 이렇게 하더라도 article_id에 저장된 값에 따라 장고 컬럼 article에 article_id에 해당하는 정보를 넣어줌
        # 저장
        comment.save()
        return redirect('articles:detail', id=article_id)
def comment_delete(request, article_id, id):
    comment=Comment.objects.get(id=id)

    comment.delete()

    return redirect('articles:detail', id=article_id)

articles/templates/detail.html
{% extends 'base.html' %}
{%block body%}

    <h1>{{article.title}}</h1>
    <p>{{article.content}}</p>

    <hr>
    <!-- app_name articles 와 path중 하나의 name comment_create 를 연결 -->
    <form action="{%url 'articles:comment_create' article_id=article.id %}" method="POST">
        {%csrf_token%}
        {{comment_form}}
        <input type="submit">
    </form>
    <!--  if not len(article.comment_set.all()) -->
    {% if not article.comment_set.all|length %}
        <p>댓글이 없습니다.</p>
    {% endif %}


    {% for comment in article.comment_set.all %}
        <!-- p태그는 블럭속성이여서 -->
        <p>{{comment.content}} <a href="{%url 'articles:comment_delete' article_id=article.id id=comment.id%}">X</a>
        
        </p>
        
    {%endfor%}


{%endblock%}

articles/templates/form.html
{% extends 'base.html' %}
{% block body%}

<form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit">

</form>


{% endblock %}

articles/templates/index.html
{% extends 'base.html' %}
{% block body %}


    {% for article in articles%}

    <p>{{article.title}}</p>
    <a href="{% url 'articles:detail' id=article.id%}">detail</a>
    <hr>
    {% endfor %}


 {% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body> 

    <a href="{%url 'articles:index' %}">Home</a>
    <a href="{%url 'articles:create' %}">Create</a>


    {% block body %}
    {% endblock %}

</body>
</html>